version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: clinica_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_backup.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d clinica_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend (FastAPI)
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://admin:${POSTGRES_PASSWORD:-admin123}@database:5432/clinica_db
      SECRET_KEY: ${SECRET_KEY:-supersegredo}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000
      "

  # Frontend (Nuxt 3)
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        NUXT_API_BASE_URL: ${NUXT_API_BASE_URL:-http://localhost:8000}
    environment:
      NUXT_API_BASE_URL: ${NUXT_API_BASE_URL:-http://localhost:8000}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: