"""Adding METODO_PAGAMENTO

Revision ID: 0b0d58e9e92a
Revises: 1bd32da6f45a
Create Date: 2025-06-15 12:34:38.292500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0d58e9e92a'
down_revision: Union[str, None] = '1bd32da6f45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ParcelasPagamento', sa.Column('metodo_pagamento', sa.String(length=20), nullable=True, comment='Como foi pago: dinheiro, cartão, transferência, pix, boleto…'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ParcelasPagamento', 'metodo_pagamento')
    # ### end Alembic commands ###
