"""Criação das tabelas iniciais

Revision ID: 13d77e6bcb54
Revises: 
Create Date: 2025-04-17 06:39:43.379460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d77e6bcb54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Utilizador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_Utilizador_id'), 'Utilizador', ['id'], unique=False)
    op.create_table('Sessao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('clinica_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('data_expiracao', sa.TIMESTAMP(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['Utilizador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UtilizadorClinica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('clinica_id', sa.Integer(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['Perfil.id'], ),
    sa.ForeignKeyConstraint(['utilizador_id'], ['Utilizador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UtilizadorClinica')
    op.drop_table('Sessao')
    op.drop_index(op.f('ix_Utilizador_id'), table_name='Utilizador')
    op.drop_table('Utilizador')
    op.drop_table('Perfil')
    # ### end Alembic commands ###
