"""Add nacionalidade tipo_documento validade_documento pais_residencia morada

Revision ID: 15c195560133
Revises: d00748370939
Create Date: 2025-04-30 10:14:13.886551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c195560133'
down_revision: Union[str, None] = 'd00748370939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Paciente', sa.Column('nacionalidade', sa.String(length=50), nullable=True))
    op.add_column('Paciente', sa.Column('tipo_documento', sa.String(length=50), nullable=True))
    op.add_column('Paciente', sa.Column('numero_documento', sa.String(length=50), nullable=True))
    op.add_column('Paciente', sa.Column('validade_documento', sa.Date(), nullable=True))
    op.add_column('Paciente', sa.Column('pais_residencia', sa.String(length=50), nullable=True))
    op.add_column('Paciente', sa.Column('morada', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'Paciente', ['numero_documento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Paciente', type_='unique')
    op.drop_column('Paciente', 'morada')
    op.drop_column('Paciente', 'pais_residencia')
    op.drop_column('Paciente', 'validade_documento')
    op.drop_column('Paciente', 'numero_documento')
    op.drop_column('Paciente', 'tipo_documento')
    op.drop_column('Paciente', 'nacionalidade')
    # ### end Alembic commands ###
