"""add_email_config_fields

Revision ID: 19966495d30e
Revises: a5cd0fca70fa
Create Date: 2025-06-22 14:02:21.368538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19966495d30e'
down_revision: Union[str, None] = 'a5cd0fca70fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClinicaEmail', sa.Column('nome_remetente', sa.String(length=100), nullable=True))
    op.add_column('ClinicaEmail', sa.Column('usar_tls', sa.Boolean(), nullable=True))
    op.add_column('ClinicaEmail', sa.Column('usar_ssl', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClinicaEmail', 'usar_ssl')
    op.drop_column('ClinicaEmail', 'usar_tls')
    op.drop_column('ClinicaEmail', 'nome_remetente')
    # ### end Alembic commands ###
