"""Adding descricao to FaturaItem

Revision ID: 1bd32da6f45a
Revises: 2459be523696
Create Date: 2025-06-15 11:08:42.516255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd32da6f45a'
down_revision: Union[str, None] = '2459be523696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FaturaItens', sa.Column('descricao', sa.String(length=255), nullable=False,server_default="Item sem descricao"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FaturaItens', 'descricao')
    # ### end Alembic commands ###
