"""Add ArtigoMedico table

Revision ID: 1f7821cba64f
Revises: d96efecba030
Create Date: 2025-05-01 14:35:41.800111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7821cba64f'
down_revision: Union[str, None] = 'd96efecba030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['Categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Artigos_codigo'), 'Artigos', ['codigo'], unique=True)
    op.create_index(op.f('ix_Artigos_id'), 'Artigos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Artigos_id'), table_name='Artigos')
    op.drop_index(op.f('ix_Artigos_codigo'), table_name='Artigos')
    op.drop_table('Artigos')
    # ### end Alembic commands ###
