"""Adding FaturaPagamento

Revision ID: 24355555ec5d
Revises: 0b0d58e9e92a
Create Date: 2025-06-19 12:29:49.636437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24355555ec5d'
down_revision: Union[str, None] = '0b0d58e9e92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fatura_pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=False),
    sa.Column('metodo_pagamento', sa.String(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fatura_id'], ['Faturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fatura_pagamentos_id'), 'fatura_pagamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fatura_pagamentos_id'), table_name='fatura_pagamentos')
    op.drop_table('fatura_pagamentos')
    # ### end Alembic commands ###
