"""Addin Fatura, FaturaItem, ParcelaPagamento tables

Revision ID: 2459be523696
Revises: e7e21011f5e1
Create Date: 2025-06-14 12:28:26.365077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2459be523696'
down_revision: Union[str, None] = 'e7e21011f5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Faturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo', sa.Enum('consulta', 'plano', name='faturatipo'), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('plano_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('pendente', 'parcial', 'paga', 'cancelada', name='faturaestado'), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['Consultas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['Paciente.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['PlanoTratamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Faturas_id'), 'Faturas', ['id'], unique=False)
    op.create_table('FaturaItens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('origem_tipo', sa.String(length=20), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['fatura_id'], ['Faturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FaturaItens_id'), 'FaturaItens', ['id'], unique=False)
    op.create_table('ParcelasPagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('valor_planejado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('pendente', 'parcial', 'paga', name='parcelaestado'), nullable=False),
    sa.ForeignKeyConstraint(['fatura_id'], ['Faturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ParcelasPagamento_id'), 'ParcelasPagamento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ParcelasPagamento_id'), table_name='ParcelasPagamento')
    op.drop_table('ParcelasPagamento')
    op.drop_index(op.f('ix_FaturaItens_id'), table_name='FaturaItens')
    op.drop_table('FaturaItens')
    op.drop_index(op.f('ix_Faturas_id'), table_name='Faturas')
    op.drop_table('Faturas')
    # ### end Alembic commands ###
