"""Changing to enum type metodo_pagamento

Revision ID: 25664207f5f5
Revises: c0c5de00799f
Create Date: 2025-06-21 03:20:52.209658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '25664207f5f5'
down_revision: Union[str, None] = 'c0c5de00799f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Create the enum type first
    op.execute("""
    CREATE TYPE metodopagamento AS ENUM (
        'dinheiro', 'cartao', 'transferencia')
    """)
    
    # Now we can safely alter columns to use the new enum type
    # Use raw SQL with USING clause for explicit casting
    op.execute("""
    ALTER TABLE "CaixaPayments" 
    ALTER COLUMN metodo_pagamento TYPE metodopagamento 
    USING metodo_pagamento::metodopagamento
    """)
    
    op.execute("""
    ALTER TABLE "ParcelasPagamento" 
    ALTER COLUMN metodo_pagamento TYPE metodopagamento 
    USING metodo_pagamento::metodopagamento
    """)
    
    op.execute("""
    ALTER TABLE "fatura_pagamentos" 
    ALTER COLUMN metodo_pagamento TYPE metodopagamento 
    USING metodo_pagamento::metodopagamento
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fatura_pagamentos', 'metodo_pagamento',
               existing_type=sa.Enum('dinheiro', 'cartao', 'transferencia', name='metodopagamento'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('ParcelasPagamento', 'metodo_pagamento',
               existing_type=sa.Enum('dinheiro', 'cartao', 'transferencia', name='metodopagamento'),
               type_=sa.VARCHAR(length=20),
               comment='Como foi pago: dinheiro, cartão, transferência, pix, boleto…',
               existing_nullable=True)
    op.alter_column('CaixaPayments', 'metodo_pagamento',
               existing_type=sa.Enum('dinheiro', 'cartao', 'transferencia', name='metodopagamento'),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
