"""Criando as tabelas Clinica, ClinicaEmail, ClinicaConfiguracoes

Revision ID: 2988e8869fbf
Revises: 8dc52e0a0457
Create Date: 2025-04-18 19:16:16.003653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2988e8869fbf'
down_revision: Union[str, None] = '8dc52e0a0457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clinica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email_envio', sa.String(length=100), nullable=True),
    sa.Column('morada', sa.Text(), nullable=True),
    sa.Column('clinica_pai_id', sa.Integer(), nullable=True),
    sa.Column('partilha_dados', sa.Boolean(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinica_pai_id'], ['Clinica.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['Utilizador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ClinicaConfiguracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=True),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['clinica_id'], ['Clinica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ClinicaEmail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=True),
    sa.Column('remetente', sa.String(length=100), nullable=True),
    sa.Column('smtp_host', sa.String(length=100), nullable=True),
    sa.Column('smtp_porta', sa.Integer(), nullable=True),
    sa.Column('utilizador_smtp', sa.String(length=100), nullable=True),
    sa.Column('password_smtp', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['Clinica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClinicaEmail')
    op.drop_table('ClinicaConfiguracao')
    op.drop_table('Clinica')
    # ### end Alembic commands ###
