"""Add tables ItemStock MovimentoStock ItemFilial

Revision ID: 37b6e5b902c3
Revises: d738994bee7d
Create Date: 2025-04-26 19:13:55.657014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b6e5b902c3'
down_revision: Union[str, None] = 'd738994bee7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItemStock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('quantidade_minima', sa.Integer(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('tipo_medida', sa.String(length=30), nullable=False),
    sa.Column('fornecedor', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['Clinica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemFilial',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['Clinica.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['ItemStock.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'filial_id')
    )
    op.create_table('MovimentoStock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimento', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('justificacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['ItemStock.id'], ),
    sa.ForeignKeyConstraint(['utilizador_id'], ['Utilizador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MovimentoStock')
    op.drop_table('ItemFilial')
    op.drop_table('ItemStock')
    # ### end Alembic commands ###
