"""Adicionando Fk em UtilizadorClinica

Revision ID: 3ed22d50eccf
Revises: 83a7df653ed9
Create Date: 2025-04-23 07:55:49.810273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed22d50eccf'
down_revision: Union[str, None] = '83a7df653ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Sessao', 'Clinica', ['clinica_id'], ['id'])
    op.create_foreign_key(None, 'UtilizadorClinica', 'Clinica', ['clinica_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UtilizadorClinica', type_='foreignkey')
    op.drop_constraint(None, 'Sessao', type_='foreignkey')
    # ### end Alembic commands ###
