"""add face_count to ArtigoMedico

Revision ID: 467d8b5c07e4
Revises: 95bc67f14ffa
Create Date: 2025-05-18 14:07:32.574531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467d8b5c07e4'
down_revision: Union[str, None] = '95bc67f14ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artigos', sa.Column('face_count', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artigos', 'face_count')
    # ### end Alembic commands ###
