"""add data_inicio e fim Marcacoes

Revision ID: 51e953fde920
Revises: 174c00631a72
Create Date: 2025-05-22 18:55:58.529093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e953fde920'
down_revision: Union[str, None] = '174c00631a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Marcacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('agendada_por', sa.Integer(), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agendada_por'], ['Utilizador.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['Clinica.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['Entidades.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['Utilizador.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['Paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Marcacoes_id'), 'Marcacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Marcacoes_id'), table_name='Marcacoes')
    op.drop_table('Marcacoes')
    # ### end Alembic commands ###
