"""Add Table ItemLote

Revision ID: 5272a5a90c25
Revises: 3bb3d437b47f
Create Date: 2025-04-28 11:02:53.972225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5272a5a90c25'
down_revision: Union[str, None] = '3bb3d437b47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItemLote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['ItemStock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('ItemStock', 'validade')
    op.drop_column('ItemStock', 'lote')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ItemStock', sa.Column('lote', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ItemStock', sa.Column('validade', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_table('ItemLote')
    # ### end Alembic commands ###
