"""Extend FichaClinica com campos do questionario

Revision ID: 56868a4a9eb4
Revises: 15c195560133
Create Date: 2025-04-30 12:48:39.030015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56868a4a9eb4'
down_revision: Union[str, None] = '15c195560133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FichaClinica', sa.Column('estado_civil', sa.String(length=50), nullable=True))
    op.add_column('FichaClinica', sa.Column('profissao', sa.String(length=100), nullable=True))
    op.add_column('FichaClinica', sa.Column('endereco', sa.Text(), nullable=True))
    op.add_column('FichaClinica', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.add_column('FichaClinica', sa.Column('local_trabalho', sa.String(length=100), nullable=True))
    op.add_column('FichaClinica', sa.Column('telefone_trabalho', sa.String(length=20), nullable=True))
    op.add_column('FichaClinica', sa.Column('tipo_beneficiario', sa.String(length=50), nullable=True))
    op.add_column('FichaClinica', sa.Column('numero_beneficiario', sa.String(length=50), nullable=True))
    op.add_column('FichaClinica', sa.Column('recomendado_por', sa.String(length=100), nullable=True))
    op.add_column('FichaClinica', sa.Column('data_questionario', sa.Date(), nullable=True))
    op.add_column('FichaClinica', sa.Column('queixa_principal', sa.Text(), nullable=True))
    op.add_column('FichaClinica', sa.Column('historia_medica', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Respostas às perguntas de História Médica e Odontológica'))
    op.add_column('FichaClinica', sa.Column('exame_clinico', sa.Text(), nullable=True))
    op.add_column('FichaClinica', sa.Column('plano_geral', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Mapa dentário e anotações por dente'))
    op.add_column('FichaClinica', sa.Column('observacoes_finais', sa.Text(), nullable=True))
    op.add_column('FichaClinica', sa.Column('responsavel_atualizacao_id', sa.Integer(), nullable=True))
    op.add_column('FichaClinica', sa.Column('data_atualizacao', sa.DateTime(), nullable=True))
    op.alter_column('FichaClinica', 'paciente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('FichaClinica', 'responsavel_criacao_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'FichaClinica', 'Utilizador', ['responsavel_atualizacao_id'], ['id'])
    op.drop_column('FichaClinica', 'observacoes_gerais')
    op.drop_column('FichaClinica', 'alergias')
    op.drop_column('FichaClinica', 'historico_medico')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FichaClinica', sa.Column('historico_medico', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('FichaClinica', sa.Column('alergias', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('FichaClinica', sa.Column('observacoes_gerais', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'FichaClinica', type_='foreignkey')
    op.alter_column('FichaClinica', 'responsavel_criacao_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('FichaClinica', 'paciente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('FichaClinica', 'data_atualizacao')
    op.drop_column('FichaClinica', 'responsavel_atualizacao_id')
    op.drop_column('FichaClinica', 'observacoes_finais')
    op.drop_column('FichaClinica', 'plano_geral')
    op.drop_column('FichaClinica', 'exame_clinico')
    op.drop_column('FichaClinica', 'historia_medica')
    op.drop_column('FichaClinica', 'queixa_principal')
    op.drop_column('FichaClinica', 'data_questionario')
    op.drop_column('FichaClinica', 'recomendado_por')
    op.drop_column('FichaClinica', 'numero_beneficiario')
    op.drop_column('FichaClinica', 'tipo_beneficiario')
    op.drop_column('FichaClinica', 'telefone_trabalho')
    op.drop_column('FichaClinica', 'local_trabalho')
    op.drop_column('FichaClinica', 'telefone')
    op.drop_column('FichaClinica', 'endereco')
    op.drop_column('FichaClinica', 'profissao')
    op.drop_column('FichaClinica', 'estado_civil')
    # ### end Alembic commands ###
