"""Add codigo-descricao unique together

Revision ID: 8243a746f1f8
Revises: efbd08ac965d
Create Date: 2025-05-03 10:39:55.289042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8243a746f1f8'
down_revision: Union[str, None] = 'efbd08ac965d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_codigo_descricao', 'Artigos', type_='unique')
    op.create_unique_constraint('uix_codigo_descricao_categoria', 'Artigos', ['codigo', 'descricao', 'categoria_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_codigo_descricao_categoria', 'Artigos', type_='unique')
    op.create_unique_constraint('uix_codigo_descricao', 'Artigos', ['codigo', 'descricao'])
    # ### end Alembic commands ###
