"""Criando novos campos do utilizador

Revision ID: 8cfcdae42284
Revises: 13d77e6bcb54
Create Date: 2025-04-17 08:45:59.091244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cfcdae42284'
down_revision: Union[str, None] = '13d77e6bcb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Utilizador', sa.Column('tentativas_falhadas', sa.Integer(), nullable=True))
    op.add_column('Utilizador', sa.Column('bloqueado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Utilizador', 'bloqueado')
    op.drop_column('Utilizador', 'tentativas_falhadas')
    # ### end Alembic commands ###
