"""Alteração dos campos Auditoria

Revision ID: 8dc52e0a0457
Revises: cc840ed56733
Create Date: 2025-04-18 14:28:20.913933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc52e0a0457'
down_revision: Union[str, None] = 'cc840ed56733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Auditoria', sa.Column('objeto', sa.String(length=100), nullable=False))
    op.add_column('Auditoria', sa.Column('objeto_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Auditoria', 'objeto_id')
    op.drop_column('Auditoria', 'objeto')
    # ### end Alembic commands ###
