"""alterar_face_para_array

Revision ID: 95bc67f14ffa
Revises: b71b64517a21
Create Date: 2025-05-18 11:55:06.319549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95bc67f14ffa'
down_revision: Union[str, None] = 'b71b64517a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrcamentoItens', 'face',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.ARRAY(sa.TEXT()),
               postgresql_using="ARRAY[face]::TEXT[]",  # Adicione esta linha
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrcamentoItens', 'face',
               existing_type=sa.ARRAY(sa.TEXT()),
               type_=sa.VARCHAR(length=1),
               postgresql_using="face[1]",  # Pegará o primeiro elemento do array
               existing_nullable=True)
    # ### end Alembic commands ###
