"""Remove quantidade_atual from ItemStock

Revision ID: 97526305b324
Revises: 5272a5a90c25
Create Date: 2025-04-28 11:33:33.763751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97526305b324'
down_revision: Union[str, None] = '5272a5a90c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ItemStock', 'quantidade_atual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ItemStock', sa.Column('quantidade_atual', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
