"""additional changes in Thread table

Revision ID: 9f722535de6b
Revises: c38e7792ed9e
Create Date: 2025-06-23 12:02:07.230072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f722535de6b'
down_revision: Union[str, None] = 'c38e7792ed9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Threads', sa.Column('nome', sa.String(length=50), nullable=True))
    op.add_column('Threads', sa.Column('tipo', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Threads', 'tipo')
    op.drop_column('Threads', 'nome')
    # ### end Alembic commands ###
