"""test

Revision ID: a5cd0fca70fa
Revises: 25664207f5f5
Create Date: 2025-06-21 03:44:28.621767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5cd0fca70fa'
down_revision: Union[str, None] = '25664207f5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CaixaPayments', 'metodo_pagamento',
               existing_type=postgresql.ENUM('dinheiro', 'cartao', 'transferencia', name='metodopagamento'),
               nullable=True)
    op.alter_column('ParcelasPagamento', 'metodo_pagamento',
               existing_type=postgresql.ENUM('dinheiro', 'cartao', 'transferencia', name='metodopagamento'),
               comment=None,
               existing_comment='Como foi pago: dinheiro, cartão, transferência, pix, boleto…',
               existing_nullable=True)
    op.alter_column('fatura_pagamentos', 'metodo_pagamento',
               existing_type=postgresql.ENUM('dinheiro', 'cartao', 'transferencia', name='metodopagamento'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fatura_pagamentos', 'metodo_pagamento',
               existing_type=postgresql.ENUM('dinheiro', 'cartao', 'transferencia', name='metodopagamento'),
               nullable=False)
    op.alter_column('ParcelasPagamento', 'metodo_pagamento',
               existing_type=postgresql.ENUM('dinheiro', 'cartao', 'transferencia', name='metodopagamento'),
               comment='Como foi pago: dinheiro, cartão, transferência, pix, boleto…',
               existing_nullable=True)
    op.alter_column('CaixaPayments', 'metodo_pagamento',
               existing_type=postgresql.ENUM('dinheiro', 'cartao', 'transferencia', name='metodopagamento'),
               nullable=False)
    # ### end Alembic commands ###
