"""Add valor_paciente column

Revision ID: b33f2d423686
Revises: fce1b70c2693
Create Date: 2025-05-03 13:33:31.103469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33f2d423686'
down_revision: Union[str, None] = 'fce1b70c2693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Precos', sa.Column('valor_entidade', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('Precos', 'valor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Precos', sa.Column('valor', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('Precos', 'valor_entidade')
    # ### end Alembic commands ###
