"""Criando nome unico para perfis

Revision ID: bd61e6555beb
Revises: e992aa8abcd1
Create Date: 2025-04-18 11:50:40.920419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd61e6555beb'
down_revision: Union[str, None] = 'e992aa8abcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Perfil', ['nome'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Perfil', type_='unique')
    # ### end Alembic commands ###
