"""CaixaSession CashierPayment Tables

Revision ID: c0c5de00799f
Revises: 24355555ec5d
Create Date: 2025-06-20 13:39:18.140843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c5de00799f'
down_revision: Union[str, None] = '24355555ec5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CaixaSessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operador_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valor_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('aberto', 'fechado', name='caixastatus'), nullable=False),
    sa.Column('valor_final', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_fecho', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operador_id'], ['Utilizador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CaixaSessions_id'), 'CaixaSessions', ['id'], unique=False)
    op.create_table('CaixaPayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=True),
    sa.Column('parcela_id', sa.Integer(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('operador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fatura_id'], ['Faturas.id'], ),
    sa.ForeignKeyConstraint(['operador_id'], ['Utilizador.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['ParcelasPagamento.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['CaixaSessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CaixaPayments_id'), 'CaixaPayments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CaixaPayments_id'), table_name='CaixaPayments')
    op.drop_table('CaixaPayments')
    op.drop_index(op.f('ix_CaixaSessions_id'), table_name='CaixaSessions')
    op.drop_table('CaixaSessions')
    # ### end Alembic commands ###
