"""additional schema changes

Revision ID: c38e7792ed9e
Revises: f1b0deacb90a
Create Date: 2025-06-23 11:14:15.657443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38e7792ed9e'
down_revision: Union[str, None] = 'f1b0deacb90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('participante_a_id', sa.Integer(), nullable=True),
    sa.Column('participante_b_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['Clinica.id'], ),
    sa.ForeignKeyConstraint(['participante_a_id'], ['Utilizador.id'], ),
    sa.ForeignKeyConstraint(['participante_b_id'], ['Utilizador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_pair_clinica', 'Threads', ['clinica_id', 'participante_a_id', 'participante_b_id'], unique=True)
    op.create_table('Mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['Clinica.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['Utilizador.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['Threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Mensagens')
    op.drop_index('ix_threads_pair_clinica', table_name='Threads')
    op.drop_table('Threads')
    # ### end Alembic commands ###
