"""add tabelas de orcamento

Revision ID: c5aabcbb7ca8
Revises: 377a886cd1c9
Create Date: 2025-05-16 23:16:19.641790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5aabcbb7ca8'
down_revision: Union[str, None] = '377a886cd1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('rascunho', 'aprovado', 'rejeitado', name='estadoorc'), nullable=False),
    sa.Column('total_entidade', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_paciente', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['Entidades.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['Paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OrcamentoItens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('artigo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_entidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_paciente', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_entidade', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_paciente', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('numero_dente', sa.SmallInteger(), nullable=True),
    sa.Column('face', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['artigo_id'], ['Artigos.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['Orcamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('Dentes', 'classe',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Dentes', 'classe',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_table('OrcamentoItens')
    op.drop_table('Orcamentos')
    # ### end Alembic commands ###
