"""Criando Auditoria Model

Revision ID: cc840ed56733
Revises: bd61e6555beb
Create Date: 2025-04-18 14:12:10.366410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc840ed56733'
down_revision: Union[str, None] = 'bd61e6555beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('detalhes', sa.String(length=255), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['Utilizador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Auditoria')
    # ### end Alembic commands ###
