"""Add tables Paciente FichaClinica AnotacaoClinica FicheiroClinico PlanoTratamento ConsultaPlanoTratamento

Revision ID: d00748370939
Revises: 97526305b324
Create Date: 2025-04-29 17:09:13.316884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00748370939'
down_revision: Union[str, None] = '97526305b324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['Clinica.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nif'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('FichaClinica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('observacoes_gerais', sa.Text(), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('historico_medico', sa.Text(), nullable=True),
    sa.Column('responsavel_criacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['Paciente.id'], ),
    sa.ForeignKeyConstraint(['responsavel_criacao_id'], ['Utilizador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlanoTratamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['Paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AnotacaoClinica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('data', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ficha_id'], ['FichaClinica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ConsultaPlanoTratamento',
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['PlanoTratamento.id'], ),
    sa.PrimaryKeyConstraint('plano_id')
    )
    op.create_table('FicheiroClinico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('caminho_ficheiro', sa.Text(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ficha_id'], ['FichaClinica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FicheiroClinico')
    op.drop_table('ConsultaPlanoTratamento')
    op.drop_table('AnotacaoClinica')
    op.drop_table('PlanoTratamento')
    op.drop_table('FichaClinica')
    op.drop_table('Paciente')
    # ### end Alembic commands ###
