"""Add relationships between Paciente and Consulta

Revision ID: d64c26420f38
Revises: fee11800b1cb
Create Date: 2025-06-02 20:11:53.086118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64c26420f38'
down_revision: Union[str, None] = 'fee11800b1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AnotacaoClinica', sa.Column('consulta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'AnotacaoClinica', 'Consultas', ['consulta_id'], ['id'])
    op.add_column('ConsultaPlanoTratamento', sa.Column('consulta_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ConsultaPlanoTratamento', 'Consultas', ['consulta_id'], ['id'])
    op.add_column('FicheiroClinico', sa.Column('consulta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'FicheiroClinico', 'Consultas', ['consulta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'FicheiroClinico', type_='foreignkey')
    op.drop_column('FicheiroClinico', 'consulta_id')
    op.drop_constraint(None, 'ConsultaPlanoTratamento', type_='foreignkey')
    op.drop_column('ConsultaPlanoTratamento', 'consulta_id')
    op.drop_constraint(None, 'AnotacaoClinica', type_='foreignkey')
    op.drop_column('AnotacaoClinica', 'consulta_id')
    # ### end Alembic commands ###
