"""Make chave unique  in ClinicaConfiguracao

Revision ID: d738994bee7d
Revises: 0e9218119664
Create Date: 2025-04-26 10:44:24.917103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd738994bee7d'
down_revision: Union[str, None] = '0e9218119664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_clinica_id_chave', 'ClinicaConfiguracao', ['clinica_id', 'chave'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_clinica_id_chave', 'ClinicaConfiguracao', type_='unique')
    # ### end Alembic commands ###
