"""Add Entidade table

Revision ID: d96efecba030
Revises: 440e1e444041
Create Date: 2025-05-01 13:26:25.987427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96efecba030'
down_revision: Union[str, None] = '440e1e444041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Categorias_id'), 'Categorias', ['id'], unique=False)
    op.create_index(op.f('ix_Categorias_slug'), 'Categorias', ['slug'], unique=True)
    op.create_table('Entidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Entidades_id'), 'Entidades', ['id'], unique=False)
    op.create_index(op.f('ix_Entidades_slug'), 'Entidades', ['slug'], unique=True)
    op.drop_index('ix_categorias_id', table_name='categorias')
    op.drop_index('ix_categorias_slug', table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categorias_pkey')
    )
    op.create_index('ix_categorias_slug', 'categorias', ['slug'], unique=True)
    op.create_index('ix_categorias_id', 'categorias', ['id'], unique=False)
    op.drop_index(op.f('ix_Entidades_slug'), table_name='Entidades')
    op.drop_index(op.f('ix_Entidades_id'), table_name='Entidades')
    op.drop_table('Entidades')
    op.drop_index(op.f('ix_Categorias_slug'), table_name='Categorias')
    op.drop_index(op.f('ix_Categorias_id'), table_name='Categorias')
    op.drop_table('Categorias')
    # ### end Alembic commands ###
