"""Add Precos table

Revision ID: dcdadc3840c9
Revises: 8243a746f1f8
Create Date: 2025-05-03 13:01:09.169587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdadc3840c9'
down_revision: Union[str, None] = '8243a746f1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Precos',
    sa.Column('artigo_id', sa.Integer(), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['artigo_id'], ['Artigos.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['Entidades.id'], ),
    sa.PrimaryKeyConstraint('artigo_id', 'entidade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Precos')
    # ### end Alembic commands ###
