"""Add PlanoItem

Revision ID: e7e21011f5e1
Revises: d64c26420f38
Create Date: 2025-06-03 21:10:30.995687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e21011f5e1'
down_revision: Union[str, None] = 'd64c26420f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PlanoItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('orcamento_item_id', sa.Integer(), nullable=False),
    sa.Column('artigo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_prevista', sa.Integer(), nullable=False),
    sa.Column('numero_dente', sa.SmallInteger(), nullable=True),
    sa.Column('face', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('quantidade_executada', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['artigo_id'], ['Artigos.id'], ),
    sa.ForeignKeyConstraint(['orcamento_item_id'], ['OrcamentoItens.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['PlanoTratamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PlanoItem_id'), 'PlanoItem', ['id'], unique=False)
    op.drop_table('ConsultaPlanoTratamento')
    op.add_column('PlanoTratamento', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('PlanoTratamento', sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('PlanoTratamento', 'paciente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('PlanoTratamento', 'estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_PlanoTratamento_id'), 'PlanoTratamento', ['id'], unique=False)
    op.drop_column('PlanoTratamento', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PlanoTratamento', sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_PlanoTratamento_id'), table_name='PlanoTratamento')
    op.alter_column('PlanoTratamento', 'estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('PlanoTratamento', 'paciente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('PlanoTratamento', 'data_conclusao')
    op.drop_column('PlanoTratamento', 'data_criacao')
    op.create_table('ConsultaPlanoTratamento',
    sa.Column('plano_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consulta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['Consultas.id'], name='ConsultaPlanoTratamento_consulta_id_fkey'),
    sa.ForeignKeyConstraint(['plano_id'], ['PlanoTratamento.id'], name='ConsultaPlanoTratamento_plano_id_fkey'),
    sa.PrimaryKeyConstraint('plano_id', name='ConsultaPlanoTratamento_pkey')
    )
    op.drop_index(op.f('ix_PlanoItem_id'), table_name='PlanoItem')
    op.drop_table('PlanoItem')
    # ### end Alembic commands ###
