"""Add codigo-descricao unique together

Revision ID: efbd08ac965d
Revises: 1569ea3aead0
Create Date: 2025-05-02 15:44:57.383325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbd08ac965d'
down_revision: Union[str, None] = '1569ea3aead0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Artigos_codigo', table_name='Artigos')
    op.create_index(op.f('ix_Artigos_codigo'), 'Artigos', ['codigo'], unique=False)
    op.create_unique_constraint('uix_codigo_descricao', 'Artigos', ['codigo', 'descricao'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_codigo_descricao', 'Artigos', type_='unique')
    op.drop_index(op.f('ix_Artigos_codigo'), table_name='Artigos')
    op.create_index('ix_Artigos_codigo', 'Artigos', ['codigo'], unique=True)
    # ### end Alembic commands ###
