"""Add valor_paciente column

Revision ID: fce1b70c2693
Revises: dcdadc3840c9
Create Date: 2025-05-03 13:27:13.747125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce1b70c2693'
down_revision: Union[str, None] = 'dcdadc3840c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Precos', sa.Column('valor_paciente', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Precos', 'valor_paciente')
    # ### end Alembic commands ###
