"""Add Dente e Face to Items

Revision ID: fee11800b1cb
Revises: f809b61057da
Create Date: 2025-05-26 18:57:03.538010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee11800b1cb'
down_revision: Union[str, None] = 'f809b61057da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ConsultaItens', sa.Column('numero_dente', sa.SmallInteger(), nullable=True))
    op.add_column('ConsultaItens', sa.Column('face', sa.ARRAY(sa.Text()), nullable=True, comment='Faces do dente: M, D, V, L, O, I'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ConsultaItens', 'face')
    op.drop_column('ConsultaItens', 'numero_dente')
    # ### end Alembic commands ###
